### ISSUE TITLE
DiegoRodriguez_Ideas

### ISSUE THREAD

**Issue by DiegoLIRodriguez** [uprm-inso4116-2023-2024-S1/musicmap#1]
1.	If inclining towards a mobile UI, we should use a mobile-friendly framework like Flutter, who has tools for developing native OS apps in iOS and Android. 
2.     Team structure should be mainly divided in front/back end, after all members have stated their preference, arbitrary division should take place to avoid crowding any particular end.

**Comment by Adhel-Esteban1** [comment]
I love this idea. A way in which we could program for both iOS and Android. I think it's fantastic.

**Comment by DiegoLIRodriguez** [comment]
Idea dicarded since we used React Expo
