### ISSUE TITLE
Ideas for project - Jonathan Rivera

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4116-2023-2024-S1/musicmap#2]
Ideas:

1. Add another type of meeting instead of a person to person, make meetings for more people with the same type of music taste.
2. Interface function: Make a type of minigames for each user like a type of quiz that depending on your answers the app will pair you with a user with the same or similar answers.

**Comment by Adhel-Esteban1** [comment]
2 is a very interesting idea.
