### ISSUE TITLE
UI Design Idea | Adhel Esteban Rivera

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4116-2023-2024-S1/musicmap#3]
In order for the software to be good and useful, we need a simple, intuitive, and powerful UI design. For the UI to be intuitive, it has to be familiar, and simple. We can use familiar symbols like bells and houses to deliver the message of what each button does. Depending on how we see fit, we could add words below the symbols. 

I think we should also select a fitting color scheme, I'm thinking purple and white. And for dark more, purple and black. 

![Image](https://github.com/uprm-inso4116-2023-2024-S1/musicmap/assets/93483234/a3950a71-49d6-480e-bf84-3cf2d435541d)

![Image](https://github.com/uprm-inso4116-2023-2024-S1/musicmap/assets/93483234/73e7d6ae-34da-4b17-856a-2c5127a91d62)

**Comment by dlaboy** [comment]
Following up UI idea, attached will be a color pallete suggestion.  

![MMCP](https://github.com/uprm-inso4116-2023-2024-S1/musicmap/assets/89310701/7e315f3f-a217-4a7c-b980-c39c2fa27aba)

**Comment by Adhel-Esteban1** [comment]
This is a most lovely color scheme. Pretty fitting for the software's main focus!
