### ISSUE TITLE
[Class Topic] Knowledge Crunching, Learn React Expo

### ISSUE THREAD

**Issue by HectorSotelo** [uprm-inso4116-2023-2024-S1/musicmap#31]
Now that app concept is defined, create a relevant model with possible interfaces, concept maps, and approaches

- For front end, React Expo was considered as a possible framework. Work on expanding our knowledge of the platform before starting implementation.

**Comment by DiegoLIRodriguez** [comment]
Finished for first sprint. After studying the problem we were trying to address, team division and management was imminent. Front and Back end members were assigned, as well as future tasks, which included familiarizing everyone with the newborn domain definition.
