### ISSUE TITLE
General : Create new branch which Merges the Back End onto the existing Front End

### ISSUE THREAD

**Issue by dlaboy** [uprm-inso4116-2023-2024-S1/musicmap#48]
To work with other features like the **sign-up/sign-in page,** we must merge or create a Backend server to work with the existing Front End. This will also be using Express Router to be able to easily add all routes in future branches.

For this, we should create a new branch from `main` and develop or merge existing code into that new branch. Once set up, development of features like the **sign up page** can be commenced, and other backend functionalities like user profiles can be tested.

**Comment by DiegoR1** [comment]
Diego Laboy - sign up 

Diego Rosario - Log in
