### ISSUE TITLE
Maps : Obtain user location and render it in a map

### ISSUE THREAD

**Issue by AngelGonzs** [uprm-inso4116-2023-2024-S1/musicmap#61]
**Obtain user location and render it in a map** : As we've seen from the demo shared by Javier in the ⁠maps channel, one of the first things we should be working towards is to get user location permissions and rendering the coordinates. Using the **Google Maps API** and React **Expo** (check [map-view](https://docs.expo.dev/versions/latest/sdk/map-view/) documentation), we can render the coordinates in a map and view it in mobile devices.

`Note: In future iterations of this, not only will we render the user's location with a pin icon, but we should save the coordinates as well.`

**Comment by JavierMaldonado7** [comment]
Location and rendering of user in map was completed utilizing expo-location, react-native-maps and Google Maps API. The implementation created showed an accurate rendering of user location and was connected to the established front-end for a demo presentation.
