### ISSUE TITLE
Audio Share

### ISSUE THREAD

**Issue by ManuelFuertes45** [uprm-inso4116-2023-2024-S1/musicmap#7]
Apple has an audio share feature. I think this could be a good feature to add to the 'MusicMap' app.

**Comment by Adhel-Esteban1** [comment]
I think a little more elaboration on this would be great!

**Comment by DiegoR1** [comment]
Apple audio share feature info - https://support.apple.com/guide/airpods/share-audio-on-iphone-ipad-or-ipod-touch-dev3786f35c8/web

I really like this idea and I think it makes perfect sense to try and implement this in the app.
